name:                prelude
version:             0.1.0.0
github:              "ksrky/prelude"
license:             BSD3
author:              "ksrk"
maintainer:          "example@example.com"
copyright:           "2021 ksrk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ksrky/prelude#readme>

dependencies:
- base >= 4.7 && < 5
- text
- filepath
- megaparsec
- llvm-hs-pure
- llvm-hs-pretty
- parser-combinators
- containers
- binary
- haskeline

library:
  source-dirs: src

executables:
  prelude-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prelude

tests:
  prelude-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prelude
